### PR TITLE
Vehicle Prediction Notebook

### PR DESCRIPTION
**Pull request by Pedrohgv**

### CODE REVIEW

**Comment by pgrandinetti** [comment]
@Pedrohgv Thanks. This work is truly great! I reproduced it entirely and easily in Colab, and you analysis was very thorough and dedicated. Fantastic.

The notebook is ready for merge for me (I noted a few typos below that you may want to fix before I merge).
@RuggeroFabbiano Let me know if you have any comment. I will want to merge this before 3/3.

---
@Pedrohgv There's a problem with the README file. To understand it, go on the tab "Files changed" and you will see that the README is marked entirely in red. Instead, there should be only 1 line added, and show it in green.

Here's a possible way to fix the problem.

1. Reset the README file to the last commit when it was changed in the upstream repo (my repo).

```
git checkout ff190daf14f9cf63932efca3efd3a31f370e573e -- README.md
```

(You could find the commit hash doing `git log -10` and scrolling down a bit).

2. Edit the README again, by adding the line with your info.
3. `git add README.md && git commit -m "fixed readme" && git push origin main`

The PR will be automatically updated, so you can check the "Files changed" tab and see if it looks OK.

---
 
Some typos:

- The sampling time in the simulation is 5 seconds, not 15.
- In the section "initialization" you mention `plotly`, which I think you were using before but now it's nowhere.
- Can you add units to **both** axis in the histograms?
- I think "fine tunning" is a typo (double "n"). It appears multiple times.

**Comment by Pedrohgv** [comment]
@pgrandinetti  I'm really glad you liked what I've done!

I'll check those errors and typos you mentioned (sorry about those) and get back to you when I'm done.

**Comment by Pedrohgv** [comment]
Hi Pietro!

I think I've covered what we discussed. I don't know what happened but I fixed the README and notebook files and made the PR, or so I thought because only the changes to the notebook passed through so I had to commit one more time. Apart from that, I think everything is ok. Let me know if you want anything else to be modified.

**Review by RuggeroFabbiano — COMMENTED** [review]
Great notebook!
I have nothing to really comment on except for a few reading details:

- Maybe you can better explain the sentence _making the argument `frac=1`_? It's not totally clear to me.
- When you introduce the first method, you could specify what type of methods it belogs to (composition methods), since you tell us that you're going to try 3 different types of methods just before.
- A typo: ROCKET kern**a**l.
- "Buses" is a much more accepted plural for "bus".

Nice work!

**Comment by pgrandinetti** [comment]
> Great notebook!
> I have nothing to really comment on except for a few reading details:
> 
>     * Maybe you can better explain the sentence _making the argument `frac=1`_? It's not totally clear to me.
> 
>     * When you introduce the first method, you could specify what type of methods it belogs to (composition methods), since you tell us that you're going to try 3 different types of methods just before.
> 
>     * A typo: ROCKET kern**a**l.
> 
>     * "Buses" is a much more accepted plural for "bus".
> 
> 
> Nice work!

@Pedrohgv ^

Scheduled for merge on 3/3. You can fix the other things Ruggero pointed out before that, if you want.

---

@Pedrohgv you should also put your name on the article. Just below the title is a good place. See the other notebooks for examples.

**Review by pgrandinetti — APPROVED** [review]

**Comment by Pedrohgv** [comment]
@RuggeroFabbiano tanks for taking the time to review it! I'll check those issues as soon as possible and get back to you
@pgrandinetti I'll add my name, thaks for the remainder!

**Comment by Pedrohgv** [comment]
@RuggeroFabbiano I just fixed the issues you pointed out, thanks! Do you think the explanation for the randomization of the dataset is more clear now?

**Review by RuggeroFabbiano — APPROVED** [review]

**Comment by pgrandinetti** [comment]
@Pedrohgv still your name is missing!

**Comment by Pedrohgv** [comment]
@pgrandinetti I'm so sorry for forgetting that! Added name now, hope it's ok. Don't hesitate to point any other errors :)

**Pull request merged**
